POST http://localhost:5000/todo/
Content-Type: application/json

{
    "title": "Learn Python",
    "description": "Learn how to crean an API with Python and Flask"
}


GET http://localhost:5000/todo/


GET http://localhost:5000/todo/663acbe77da2692477403ca0




PUT http://localhost:5000/todo/663acbe77da2692477403ca0
Content-Type: application/json

{
   "title": "Learn Python and Flask",
   "done": true
}

DELETE http://localhost:5000/todo/663acbe77da2692477403ca0
